---
title: "README_GRAPHS"
author: "Roan Minnie"
date: "29 November 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, fig.width = 6, fig.height = 5, fig.pos="H", fig.pos = 'H')
```
#Setup 
Loading the necessary packages
```{r}
if(!require("SentimentAnalysis")) install.packages("SentimentAnalysis") 
if(!require("future")) install.packages("future")
library(rmsfuns)
load_pkg(c("tidyverse","SentimentAnalysis","tbl2xts","ggthemes","ggplot2", "furrr", "lubridate", "scales", "ggsci"))
```
#Load data
```{r}
naive <- readRDS("data/complete_naive.rds")
refine <- readRDS("data/complete_refine.rds")
library(zoo)
naive <- naive %>% 
  mutate(date = as.yearmon(naive$year_month)) %>% 
  mutate(exchange = std_freq) %>% 
  select(date, finance, market, stock, exchange, rand, JSE)

write_rds(naive, path = "data/naive_index.rds")

refine <- refine %>% 
  mutate(date = as.yearmon(refine$year_month)) %>% 
  mutate(exchange = std_freq) %>% 
  select(date, finance, market, stock, exchange, rand, JSE)

write_rds(refine, path = "data/refine_index.rds")

complete <- naive %>% 
  mutate(ri_finance = refine$finance) %>% 
  mutate(ri_market = refine$market) %>% 
  mutate(ri_stock = refine$stock) %>%
  mutate(ri_exchange = refine$exchange) %>% 
  mutate(ri_rand = refine$rand) %>% 
  mutate(ri_JSE = refine$JSE)

```


```{r}
naive_tidy <- naive %>% 
  gather(Index, values, -date)

refine_tidy<- refine %>% 
  gather(Index, values, -date)

complete_tidy <- complete %>% 
  gather(Index, values, -date)

```

#Plot for naive index
```{r}
theme_set(theme_calc())

# plot
naive_plot = ggplot(naive_tidy) + 
  geom_line(aes(x=date, y=values, colour=Index), size = 1) +
  labs(title="Naive uncertainty indices per keyword", 
       subtitle="", 
       caption="", 
       y="Index value") +  
  theme(axis.text.x = element_text(angle = 90, vjust=0.5),
        panel.grid.minor = element_blank()) +
  scale_color_futurama()

naive_plot
```

#Plot for refine index
```{r}
theme_set(theme_calc())

# plot
refine_plot = ggplot(refine_tidy) + 
  geom_line(aes(x=date, y=values, colour=Index), size = 1) +
  labs(title="Refined uncertainty indices per keyword", 
       subtitle="", 
       caption="", 
       y="Index value") +  
  theme(axis.text.x = element_text(angle = 90, vjust=0.5),
        panel.grid.minor = element_blank()) +
  scale_color_futurama()

refine_plot
```

#Plots for different criteria
##Finance
```{r}
theme_set(theme_calc())

# plot
finance_plot = ggplot(subset(complete_tidy, Index %in% c("finance","ri_finance"))) + 
  geom_line(aes(x=date, y=values, colour=Index), size = 1) +
  labs(title="Finance uncertainty indices", 
       subtitle="", 
       caption="", 
       y="Index value") +  
  theme(axis.text.x = element_text(angle = 90, vjust=0.5),
        panel.grid.minor = element_blank()) +
  scale_color_futurama()
finance_plot
```

##Market
```{r}
theme_set(theme_calc())

# plot
market_plot = ggplot(subset(complete_tidy, Index %in% c("market","ri_market"))) + 
  geom_line(aes(x=date, y=values, colour=Index), size = 1) +
  labs(title="Market uncertainty indices", 
       subtitle="", 
       caption="", 
       y="Index value") +  
  theme(axis.text.x = element_text(angle = 90, vjust=0.5),
        panel.grid.minor = element_blank()) +
  scale_color_futurama()
market_plot
```

##Stock
```{r}
theme_set(theme_calc())

# plot
stock_plot = ggplot(subset(complete_tidy, Index %in% c("stock","ri_stock"))) + 
  geom_line(aes(x=date, y=values, colour=Index), size = 1) +
  labs(title="Stock uncertainty indices", 
       subtitle="", 
       caption="", 
       y="Index value") +  
  theme(axis.text.x = element_text(angle = 90, vjust=0.5),
        panel.grid.minor = element_blank()) +
  scale_color_futurama()
stock_plot
```

##Exchange
```{r}
theme_set(theme_calc())

# plot
exchange_plot = ggplot(subset(complete_tidy, Index %in% c("exchange","ri_exchange"))) + 
  geom_line(aes(x=date, y=values, colour=Index), size = 1) +
  labs(title="Exchange uncertainty indices", 
       subtitle="", 
       caption="", 
       y="Index value") +  
  theme(axis.text.x = element_text(angle = 90, vjust=0.5),
        panel.grid.minor = element_blank()) +
  scale_color_futurama()
exchange_plot
```

##Rand
```{r}
theme_set(theme_calc())

# plot
rand_plot = ggplot(subset(complete_tidy, Index %in% c("rand","ri_rand"))) + 
  geom_line(aes(x=date, y=values, colour=Index), size = 1) +
  labs(title="Rand uncertainty indices", 
       subtitle="", 
       caption="", 
       y="Index value") +  
  theme(axis.text.x = element_text(angle = 90, vjust=0.5),
        panel.grid.minor = element_blank()) +
  scale_color_futurama()
rand_plot
```


##JSE
```{r}
theme_set(theme_calc())

# plot
JSE_plot = ggplot(subset(complete_tidy, Index %in% c("JSE","ri_JSE"))) + 
  geom_line(aes(x=date, y=values, colour=Index), size = 1) +
  labs(title="JSE uncertainty indices", 
       subtitle="", 
       caption="", 
       y="Index value") +  
  theme(axis.text.x = element_text(angle = 90, vjust=0.5),
        panel.grid.minor = element_blank()) +
  scale_color_futurama()
JSE_plot
```

#save plots
```{r}
naive_plot
ggsave("bin/naive_plot.png")
refine_plot
ggsave("bin/refine_plot.png")
finance_plot
ggsave("bin/finance_plot.png")
exchange_plot
ggsave("bin/exchange_plot.png")
stock_plot
ggsave("bin/stock_plot.png")
rand_plot
ggsave("bin/rand_plot.png")
market_plot
ggsave("bin/market_plot.png")
JSE_plot
ggsave("bin/JSE_plot.png")
```






